import { useState } from "react";
import { useTranslation } from "react-i18next";
import { UserRound } from "lucide-react";

type GuestRoom = { id: string; type: string; beds: string; guests: number };

export default function GuestRoomForms({ rooms }: { rooms: GuestRoom[] }) {
  const { t } = useTranslation();
  const [guests, setGuests] = useState<Record<string, { name: string; phone: string }>>({});
  const update = (id: string, field: "name" | "phone", value: string) => setGuests((current) => ({ ...current, [id]: { ...current[id], [field]: value } }));
  return <div className="space-y-4">{rooms.map((room, index) => <div key={room.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-3 border-b border-slate-100 pb-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-violet-100 text-xs font-bold text-violet-700"><UserRound size={16} /></div><div><p className="text-sm font-bold text-slate-900">{t("booking.stayingGuest", "Guest staying in room")} {room.id}</p><p className="mt-0.5 text-xs text-slate-500">{room.type} · {room.beds} · {t("room.maxGuestsLabel", "Up to {{count}} guests", { count: room.guests })}</p></div><span className="ml-auto rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500">{t("booking.guestNumber", "Guest {{count}}", { count: index + 1 })}</span></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">{t("customer.fullName")}<input value={guests[room.id]?.name || ""} onChange={(event) => update(room.id, "name", event.target.value)} placeholder={t("common.guestNamePlaceholder", "Nguyễn Văn A")} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label><label className="text-sm font-semibold text-slate-700">{t("customer.phone")}<input value={guests[room.id]?.phone || ""} onChange={(event) => update(room.id, "phone", event.target.value)} placeholder="090 000 0000" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold text-slate-700">{t("booking.adults")}<select defaultValue="2" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label className="text-sm font-semibold text-slate-700">{t("booking.children")}<select defaultValue="0" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal"><option>0</option><option>1</option><option>2</option></select></label><label className="text-sm font-semibold text-slate-700">{t("booking.infants")}<select defaultValue="0" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal"><option>0</option><option>1</option><option>2</option></select></label></div><label className="mt-4 block text-sm font-semibold text-slate-700">{t("booking.privateNote", "Private note for room")} {room.id}<textarea rows={2} placeholder={t("booking.specialRequest", "Special guest requests...")} className="mt-1.5 w-full resize-none rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-violet-400" /></label></div>)}</div>;
}
